// GENERATED by tool/generate_version.dart — do not edit by hand. Regenerate
// with `dart run tool/generate_version.dart` after bumping pubspec.yaml.

/// tina's version, from pubspec.yaml at build time.
const String tinaVersion = '0.4.1';
