// Regenerates lib/version.g.dart from the pubspec version so the compiled
// binary knows its own version (the pubspec isn't embedded in `dart build`
// snapshots). Run by tool/build_bundle.sh before every build; the generated
// file is also checked in so `dart run` and tests work without regenerating —
// test/version_test.dart fails when the two drift apart on a version bump.
import 'dart:io';

void main(List<String> argv) {
  final repoRoot = argv.isNotEmpty ? argv.first : '.';
  final pubspec = File('$repoRoot/pubspec.yaml');
  if (!pubspec.existsSync()) {
    stderr.writeln('error: ${pubspec.path} not found');
    exit(1);
  }
  final match =
      RegExp(r'^version:\s*(\S+)\s*$', multiLine: true).firstMatch(pubspec.readAsStringSync());
  if (match == null) {
    stderr.writeln('error: no `version:` line found in ${pubspec.path}');
    exit(1);
  }
  final version = match.group(1)!;
  final out = File('$repoRoot/lib/version.g.dart');
  out.writeAsStringSync('''
// GENERATED by tool/generate_version.dart — do not edit by hand. Regenerate
// with `dart run tool/generate_version.dart` after bumping pubspec.yaml.

/// tina's version, from pubspec.yaml at build time.
const String tinaVersion = '$version';
''');
  stdout.writeln('wrote ${out.path} (version $version)');
}
